# Aliases for reuse
aliases:
  - &working_directory ~/terminal-printer

  - &restore_npm_cache
    keys:
      - v1-terminal-printer-npm-cache-{{ checksum "yarn.lock" }}

  - &save_npm_cache
    key: v1-terminal-printer-npm-cache-{{ checksum "yarn.lock" }}
    paths:
      - node_modules

  - &install
    name: Installing
    command: yarn

  - &npm_auth_token
    name: Configure Circle to add the authToken to ~/.npmrc
    command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc

  - &reset_lockfile
    name: Reset yarn.lock
    command: git checkout yarn.lock

# Defaults for node environment
node16Environment: &node16Environment
  docker:
    - image: cimg/node:16.20
  working_directory: *working_directory

version: 2
jobs:
  install:
    <<: *node16Environment
    steps:
      - checkout
      - restore-cache: *restore_npm_cache
      - run: *install
      - run: *reset_lockfile
      - save-cache: *save_npm_cache
  lint:
    <<: *node16Environment
    steps:
      - checkout
      - restore-cache: *restore_npm_cache
      - run:
          name: "Linting"
          command: yarn lint
  test:
    <<: *node16Environment
    steps:
      - checkout
      - restore-cache: *restore_npm_cache
      - run:
          name: "Testing"
          command: yarn test
  build:
    <<: *node16Environment
    steps:
      - checkout
      - restore-cache: *restore_npm_cache
      - run:
          name: Building
          command: yarn build
      - persist_to_workspace:
          root: *working_directory
          paths:
            - packages/terminal-matrix-rain/dist
            - packages/terminal-printer/dist
            - packages/terminal-snake/dist
  publish:
    <<: *node16Environment
    steps:
      - add_ssh_keys:
          fingerprints:
            - "4e:f6:11:50:f1:a9:59:25:40:63:ef:bd:5d:cd:69:76"
      - checkout
      - restore-cache: *restore_npm_cache
      - attach_workspace:
          at: *working_directory
      - run: *npm_auth_token
      - run:
          name: Git config
          command: git config --global user.email "thomas.heyenbrock@gmail.com" && git config --global user.name "Thomas Heyenbrock"
      - run:
          name: Publishing
          command: yarn lerna publish --conventional-commits --yes
      - run:
          name: Merge master in develop
          command: git checkout develop && git merge master && git push

workflows:
  version: 2
  terminal-printer-workflow:
    jobs:
      - install
      - lint:
          requires:
            - install
      - test:
          requires:
            - install
      - build:
          requires:
            - lint
            - test
      - publish:
          requires:
            - build
          filters:
            branches:
              only: master
